--- 
title: "Introducción a la Investigación Reproducible con RStudio y RMarkdown"
date: "Julio 11-15, 2019"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    toc_depth: 3
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
description: ""
always_allow_html: yes
---

_**Reconocimiento**_: Gran parte de los documentos introductorios son una traducción libre desde al material preparado 
y compartido por el grupo [SASAP](https://alaskasalmonandpeople.org/) del [NCEAS](https://www.nceas.ucsb.edu/) en su sitio [SASAP-Training](https://github.com/NCEAS/sasap-training) de en [GitHub](https://github.com/).


# Introducción

La reproducibilidad es fundamental en la ciencia, ya que la ciencia está basada en observaciones empíricas acopladas a modelos 
explicativos. Si bien la reproducibilidad incluye el ciclo de vida completo de la ciencia y ademas incluye aspectos como la 
consistencia metodológica y tratamiento del sesgo, en este curso nos enfocaremos a la **reproducibilidad computacional**, esto
es la habilidad para documentar datos, análisis y modelos en forma suficiente para que otros investigadores sean capaces de 
entender, reproducir y re-ejecutar los pasos computacionales que llevemos a los resultados científicos y sus conclusiones. 

## La crisis de reproducibilidad

@ioannidis_why_2005 destacó la crisis en reproducilidad de la ciencia cuando escribió que "La mayoría de los 
descubrimientos son falsos para la mayoría de los diseños de investigación en la mayoría de las áreas de investigación" 
(_"Most Research Findings Are False for Most Research Designs and for Most Fields"_). Ioannidis indica la formas en que 
el proceso de investigación a inflado los efectos de los tamaños muestrales y los tests de hipótesis que codifican los 
sesgos existentes. Investigación posteriores han confirmado que la reproducibilidad es baja a través de muchos campos, 
incluyendo genética [@ioannidis_repeatability_2009], ecología [@fraser_questionable_2018], y psicología
[@open_science_collaboration_estimating_2015], entre otras. Por ejemplo, el efecto del tamaño de muestra en la psicología
se ha mostrado que decrece significativamente cuando se repiten los experimentos (\@ref(fig:effectsize)).

#### Reconocimientos

Este curso está basado en una desarrollado por el [_Arctic Data Center_](https://arcticdata.io/) en 
[_NCEAS_](http://www.nceas.ucsb.edu) y ha sido modificado y traducido con el apoyo del 
[_Instituto de Fomento Pesquero_](http://www.ifop.cl).

