
# Interfase de Usuario: Como construirla

Ahora que ya entiende la estructura de una Shiny app, es tiempo de construir la primera desde cero.


## Objetivos

- Crear una Shiny app desde cero
- Entender los principio básico del diseño de la aplicación.

En este capítulo vamos a ver como contruir una interfase de usuario para la aplicación. Aprenderá como diseñar la interfase, para luego agregar texto, imágenes y otros elementos HTML.

## Manos a la obra

Usaremos la app `MiAplicacion` del capítulo anterior. Para comenzar abra el archivo `app.R` y modifique el código para que se vea de la siguiente forma:

```
library(shiny)

# En esta sección se define la interfase de usuario y es donde haremos la mayor parte del trabajo
ui <- fluidPage(
                )

# Se define la lógica que sigue el servidor
server <- function(input, output) {
                                  }

# Ejecuta la aplición
shinyApp(ui = ui, server = server)
```

Esto código representa el mínimo posible necesario para create un Shiny app. El resultado es bastante poco util, es una aplicación vacís, sin contenido, con un espacio blanco donde debería estar la interfase de usuario y las salidas como tablas o gráficos. Es por esto que es un excelente punto de partida para el trabajo que vamos a realizar en este capítulo.

### Diseño (Layout)

Shiny usa la función `fluidPage` para crear el display que se ajusta automáticamente las dimenciones de la ventana del navegador del usuario.  Es en esta función donde se introducen los elemento necesarios para diseñar la interfase de usuario.

Por ejemplo, la función `ui` que se ve abajo, crea una interfase de usuario que tiene un panel con un título (`titlePanel`) y un diseño de barra lateral (`sidebarLayout`); incluye un panel lateral (`sidebarPanel`) y un panel principal (`mainPanel`). Hay que hacer notal que estos elemento son incluidos *dentro* de la función `fluidPage`.

```
ui <- fluidPage(
  titlePanel("Panel de Título"),
  sidebarLayout(
        sidebarPanel("Panel lateral"),
        mainPanel("Panel principal")
               )
  )
```

## Resources

- [Thinking preferences overview](files/thinking-preferences.html)
